title: "Eating habits"
# description: "Diet to 15% fat"
url: "https://petmakris.github.io"
baseurl: ""
theme: jekyll-theme-cayman
# theme: minimal-mistakes-jekyll
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: "mmistakes/minimal-mistakes@4.27.3"

permalink: /:year/:month/:day/:title/
giscus_enabled: false
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
sass:
  style: compressed
    
